// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "João Silva",
    email: "joao.silva@escola.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654321",
    subjects: ["Matemática", "Geometria"],
    classes: ["1B", "2A", "3C"],
    address: "Rua Principal, 123, São Paulo, SP",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Maria Oliveira",
    email: "maria.oliveira@escola.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654322",
    subjects: ["Física", "Química"],
    classes: ["5A", "4B", "3C"],
    address: "Rua das Flores, 456, São Paulo, SP",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Miguel Costa",
    email: "miguel.costa@escola.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654323",
    subjects: ["Biologia"],
    classes: ["5A", "4B", "3C"],
    address: "Avenida Paulista, 789, São Paulo, SP",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Júlio Fernandes",
    email: "julio.fernandes@escola.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654324",
    subjects: ["História"],
    classes: ["5A", "4B", "3C"],
    address: "Rua das Palmeiras, 321, São Paulo, SP",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Ana Souza",
    email: "ana.souza@escola.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654325",
    subjects: ["Música", "História"],
    classes: ["5A", "4B", "3C"],
    address: "Rua dos Três Corações, 202, São Paulo, SP",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Ana Santiago",
    email: "ana.santiago@escola.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654326",
    subjects: ["Física"],
    classes: ["5A", "4B", "3C"],
    address: "Rua do Sol, 567, São Paulo, SP",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Carlos Lima",
    email: "carlos.lima@escola.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654327",
    subjects: ["Inglês", "Espanhol"],
    classes: ["5A", "4B", "3C"],
    address: "Rua das Árvores, 200, São Paulo, SP",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Ophelia Castro",
    email: "opheliacastro@escola.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654328",
    subjects: ["Matemática", "Geometria"],
    classes: ["5A", "4B", "3C"],
    address: "Rua das Flores, 400, São Paulo, SP",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Ricardo Oliveira",
    email: "ricardo.oliveira@escola.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654329",
    subjects: ["Literatura", "Inglês"],
    classes: ["5A", "4B", "3C"],
    address: "Avenida Brasil, 1010, São Paulo, SP",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "João Gouveia",
    email: "joao.gouveia@escola.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654330",
    subjects: ["Biologia"],
    classes: ["5A", "4B", "3C"],
    address: "Rua dos Lagos, 133, São Paulo, SP",
  },
];


export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "João Pereira",
    email: "joao.pereira@escola.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654321",
    grade: 5,
    class: "1B",
    address: "Rua Principal, 123, São Paulo, SP",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Maria Oliveira",
    email: "maria.oliveira@escola.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654322",
    grade: 5,
    class: "5A",
    address: "Rua das Flores, 456, São Paulo, SP",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Miguel Costa",
    email: "miguel.costa@escola.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654323",
    grade: 5,
    class: "5A",
    address: "Avenida Paulista, 789, São Paulo, SP",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Júlia Santos",
    email: "julia.santos@escola.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654324",
    grade: 5,
    class: "5A",
    address: "Rua das Palmeiras, 321, São Paulo, SP",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Ana Souza",
    email: "ana.souza@escola.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654325",
    grade: 5,
    class: "5A",
    address: "Rua dos Três Corações, 202, São Paulo, SP",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Ana Santiago",
    email: "ana.santiago@escola.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654326",
    grade: 5,
    class: "5A",
    address: "Rua do Sol, 567, São Paulo, SP",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Carlos Lima",
    email: "carlos.lima@escola.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654327",
    grade: 5,
    class: "5A",
    address: "Rua das Árvores, 200, São Paulo, SP",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Ophelia Castro",
    email: "opheliacastro@escola.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654328",
    grade: 5,
    class: "5A",
    address: "Rua das Flores, 400, São Paulo, SP",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Ricardo Oliveira",
    email: "ricardo.oliveira@escola.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654329",
    grade: 5,
    class: "5A",
    address: "Avenida Brasil, 1010, São Paulo, SP",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "João Gouveia",
    email: "joao.gouveia@escola.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "987654330",
    grade: 5,
    class: "5A",
    address: "Rua dos Lagos, 133, São Paulo, SP",
  },
];


export const parentsData = [
  {
    id: 1,
    name: "João Souza",
    students: ["Sara Souza"],
    email: "joao.souza@escola.com",
    phone: "11987654321",
    address: "Rua das Flores, 123, São Paulo, SP",
  },
  {
    id: 2,
    name: "Ana Oliveira",
    students: ["Cecília Oliveira"],
    email: "ana.oliveira@escola.com",
    phone: "11987654322",
    address: "Avenida Paulista, 456, São Paulo, SP",
  },
  {
    id: 3,
    name: "Carlos Geller",
    students: ["Fanny Geller"],
    email: "carlos.geller@escola.com",
    phone: "11987654323",
    address: "Rua do Sol, 789, São Paulo, SP",
  },
  {
    id: 4,
    name: "Jay Silva",
    students: ["Mollie Silva", "Ian Silva"],
    email: "jay.silva@escola.com",
    phone: "11987654324",
    address: "Rua dos Três Corações, 1010, São Paulo, SP",
  },
  {
    id: 5,
    name: "Maria Pereira",
    students: ["Mabel Pereira"],
    email: "maria.pereira@escola.com",
    phone: "11987654325",
    address: "Rua dos Lagos, 202, São Paulo, SP",
  },
  {
    id: 6,
    name: "Ana Santiago",
    students: ["Joel Santiago"],
    email: "ana.santiago@escola.com",
    phone: "11987654326",
    address: "Rua das Palmeiras, 303, São Paulo, SP",
  },
  {
    id: 7,
    name: "Allen Costa",
    students: ["Carla Costa", "Lilian Costa"],
    email: "allen.costa@escola.com",
    phone: "11987654327",
    address: "Rua das Árvores, 404, São Paulo, SP",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexandre Castro"],
    email: "opheliacastro@escola.com",
    phone: "11987654328",
    address: "Rua das Flores, 505, São Paulo, SP",
  },
  {
    id: 9,
    name: "Derek Souza",
    students: ["Suzana Souza", "Madalena Souza"],
    email: "derek.souza@escola.com",
    phone: "11987654329",
    address: "Avenida Brasil, 606, São Paulo, SP",
  },
  {
    id: 10,
    name: "João Gouveia",
    students: ["Stella Gouveia"],
    email: "joao.gouveia@escola.com",
    phone: "11987654330",
    address: "Rua do Sol, 707, São Paulo, SP",
  },
];


export const subjectsData = [
  {
    id: 1,
    name: "Matemática",
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "Português",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Física",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Química",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Biologia",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "História",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Geografia",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Arte",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Música",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Literatura",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];


export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "José Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake José",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tomás Bento",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aarão Collier",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Franco",
  },
  {
    id: 6,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carla Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Cristóvão Butera",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marcelo Millar",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Maris",
  },
];


export const lessonsData = [
  {
    id: 1,
    subject: "Matemática",
    class: "1A",
    teacher: "Tommy Souza",
  },
  {
    id: 2,
    subject: "Português",
    class: "2A",
    teacher: "Rita Franco",
  },
  {
    id: 3,
    subject: "Ciências",
    class: "3A",
    teacher: "Diana Silva",
  },
  {
    id: 4,
    subject: "História",
    class: "1B",
    teacher: "Bruno Rodrigues",
  },
  {
    id: 5,
    subject: "Arte",
    class: "4A",
    teacher: "Beatriz Oliveira",
  },
  {
    id: 6,
    subject: "Música",
    class: "5A",
    teacher: "Benedita Souza",
  },
  {
    id: 7,
    subject: "História",
    class: "6A",
    teacher: "Hélio Silva",
  },
  {
    id: 8,
    subject: "Geografia",
    class: "6B",
    teacher: "Luciana Santos",
  },
  {
    id: 9,
    subject: "Física",
    class: "6C",
    teacher: "Ronaldo Pereira",
  },
  {
    id: 10,
    subject: "Química",
    class: "4B",
    teacher: "Júlia Costa",
  },
];


export const examsData = [
  {
    id: 1,
    subject: "Matemática",
    class: "1A",
    teacher: "Marta Silva",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "Português",
    class: "2A",
    teacher: "Ronaldo Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Ciências",
    class: "3A",
    teacher: "Myrtine Costa",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "História",
    class: "1B",
    teacher: "Alvino Silva",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Arte",
    class: "4A",
    teacher: "Mabel Oliveira",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Música",
    class: "5A",
    teacher: "Dália Santos",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "História",
    class: "6A",
    teacher: "Alessandra Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geografia",
    class: "6B",
    teacher: "Henrique Sousa",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Física",
    class: "7A",
    teacher: "Luiza Lins",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Química",
    class: "8A",
    teacher: "Vera Martins",
    date: "2025-01-01",
  },
];


export const assignmentsData = [
  {
    id: 1,
    subject: "Matemática",
    class: "1A",
    teacher: "Antônio Silva",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "Português",
    class: "2A",
    teacher: "Cláudio Pereira",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Ciências",
    class: "3A",
    teacher: "Catarina Souza",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "História",
    class: "1B",
    teacher: "Willian Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Arte",
    class: "4A",
    teacher: "José Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Música",
    class: "5A",
    teacher: "Katharine Gomes",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "História",
    class: "6A",
    teacher: "Shawn Lima",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geografia",
    class: "6B",
    teacher: "Donato Oliveira",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Física",
    class: "7A",
    teacher: "Franklin Gregório",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Química",
    class: "8A",
    teacher: "Daniela Nunes",
    dueDate: "2025-01-01",
  },
];


export const resultsData = [
  {
    id: 1,
    subject: "Matemática",
    class: "1A",
    teacher: "João Souza",
    student: "João Souza",
    date: "2025-01-01",
    type: "prova",
    score: 90,
  },
  {
    id: 2,
    subject: "Português",
    class: "2A",
    teacher: "João Souza",
    student: "João Souza",
    date: "2025-01-01",
    type: "prova",
    score: 90,
  },
  {
    id: 3,
    subject: "Ciências",
    class: "3A",
    teacher: "João Souza",
    student: "João Souza",
    date: "2025-01-01",
    type: "prova",
    score: 90,
  },
  {
    id: 4,
    subject: "História",
    class: "1B",
    teacher: "João Souza",
    student: "João Souza",
    date: "2025-01-01",
    type: "prova",
    score: 90,
  },
  {
    id: 5,
    subject: "Arte",
    class: "4A",
    teacher: "João Souza",
    student: "João Souza",
    date: "2025-01-01",
    type: "prova",
    score: 90,
  },
  {
    id: 6,
    subject: "Música",
    class: "5A",
    teacher: "João Souza",
    student: "João Souza",
    date: "2025-01-01",
    type: "prova",
    score: 90,
  },
  {
    id: 7,
    subject: "História",
    class: "6A",
    teacher: "João Souza",
    student: "João Souza",
    date: "2025-01-01",
    type: "prova",
    score: 90,
  },
  {
    id: 8,
    subject: "Geografia",
    class: "6B",
    teacher: "João Souza",
    student: "João Souza",
    date: "2025-01-01",
    type: "prova",
    score: 90,
  },
  {
    id: 9,
    subject: "Física",
    class: "7A",
    teacher: "João Souza",
    student: "João Souza",
    date: "2025-01-01",
    type: "prova",
    score: 90,
  },
  {
    id: 10,
    subject: "Química",
    class: "8A",
    teacher: "João Souza",
    student: "João Souza",
    date: "2025-01-01",
    type: "prova",
    score: 90,
  },
];


export const eventsData = [
  {
    id: 1,
    title: "Passeio ao Lago",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Piquenique",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Passeio à Praia",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Visita ao Museu",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Concerto de Música",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Show de Mágica",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Passeio ao Lago",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Corrida de Bicicleta",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Exposição de Arte",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Campeonato Esportivo",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];


export const announcementsData = [
  {
    id: 1,
    title: "Sobre a Prova de Matemática de 4A",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "Sobre a Prova de Matemática de 3A",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "Sobre a Prova de Matemática de 3B",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "Sobre a Prova de Matemática de 6A",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "Sobre a Prova de Matemática de 8C",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "Sobre a Prova de Matemática de 2A",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "Sobre a Prova de Matemática de 4C",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "Sobre a Prova de Matemática de 4B",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "Sobre a Prova de Matemática de 3C",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "Sobre a Prova de Matemática de 1C",
    class: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Matemática",
    allDay: false,
    start: new Date(2024, 11, 5, 8, 0),  // 5 de dezembro de 2024
    end: new Date(2024, 11, 5, 8, 45),
  },
  {
    title: "Português",
    allDay: false,
    start: new Date(2024, 11, 5, 9, 0),
    end: new Date(2024, 11, 5, 9, 45),
  },
  {
    title: "Biologia",
    allDay: false,
    start: new Date(2024, 11, 5, 10, 0),
    end: new Date(2024, 11, 5, 10, 45),
  },
  {
    title: "Física",
    allDay: false,
    start: new Date(2024, 11, 5, 11, 0),
    end: new Date(2024, 11, 5, 11, 45),
  },
  {
    title: "Química",
    allDay: false,
    start: new Date(2024, 11, 5, 13, 0),
    end: new Date(2024, 11, 5, 13, 45),
  },
  {
    title: "História",
    allDay: false,
    start: new Date(2024, 11, 5, 14, 0),
    end: new Date(2024, 11, 5, 14, 45),
  },
  {
    title: "Português",
    allDay: false,
    start: new Date(2024, 11, 6, 9, 0),
    end: new Date(2024, 11, 6, 9, 45),
  },
  {
    title: "Biologia",
    allDay: false,
    start: new Date(2024, 11, 6, 10, 0),
    end: new Date(2024, 11, 6, 10, 45),
  },
  {
    title: "Física",
    allDay: false,
    start: new Date(2024, 11, 6, 11, 0),
    end: new Date(2024, 11, 6, 11, 45),
  },
  {
    title: "História",
    allDay: false,
    start: new Date(2024, 11, 6, 14, 0),
    end: new Date(2024, 11, 6, 14, 45),
  },
  {
    title: "Matemática",
    allDay: false,
    start: new Date(2024, 11, 7, 8, 0),
    end: new Date(2024, 11, 7, 8, 45),
  },
  {
    title: "Biologia",
    allDay: false,
    start: new Date(2024, 11, 7, 10, 0),
    end: new Date(2024, 11, 7, 10, 45),
  },
  {
    title: "Química",
    allDay: false,
    start: new Date(2024, 11, 7, 13, 0),
    end: new Date(2024, 11, 7, 13, 45),
  },
  {
    title: "História",
    allDay: false,
    start: new Date(2024, 11, 7, 14, 0),
    end: new Date(2024, 11, 7, 14, 45),
  },
  {
    title: "Português",
    allDay: false,
    start: new Date(2024, 11, 8, 9, 0),
    end: new Date(2024, 11, 8, 9, 45),
  },
  {
    title: "Biologia",
    allDay: false,
    start: new Date(2024, 11, 8, 10, 0),
    end: new Date(2024, 11, 8, 10, 45),
  },
  {
    title: "Física",
    allDay: false,
    start: new Date(2024, 11, 8, 11, 0),
    end: new Date(2024, 11, 8, 11, 45),
  },
  {
    title: "História",
    allDay: false,
    start: new Date(2024, 11, 8, 14, 0),
    end: new Date(2024, 11, 8, 14, 45),
  },
  {
    title: "Matemática",
    allDay: false,
    start: new Date(2024, 11, 9, 8, 0),
    end: new Date(2024, 11, 9, 8, 45),
  },
  {
    title: "Português",
    allDay: false,
    start: new Date(2024, 11, 9, 9, 0),
    end: new Date(2024, 11, 9, 9, 45),
  },
  {
    title: "Física",
    allDay: false,
    start: new Date(2024, 11, 9, 11, 0),
    end: new Date(2024, 11, 9, 11, 45),
  },
  {
    title: "Química",
    allDay: false,
    start: new Date(2024, 11, 9, 13, 0),
    end: new Date(2024, 11, 9, 13, 45),
  },
  {
    title: "História",
    allDay: false,
    start: new Date(2024, 11, 9, 14, 0),
    end: new Date(2024, 11, 9, 14, 45),
  },
];
